---
title: "ARIMA Modelling"
author: "Alan Mathew"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
set.seed(20717559)

mse = function(y_true, y_pred){
    mean((y_true - y_pred)^2)
}
```

```{r}
library(astsa)

train = read.csv('train.csv')
Y_train = ts(train$price)
pwrY_train = Y_train^0.075
```

```{r}
plot(pwrY_train, main="Power transformed bitcoin price", ylab="power transformed bitcoin price ($ USD)")
```

```{r}
diffY_train = diff(pwrY_train)
plot(diffY_train, main="Twice differenced power transformed bitcoin price", ylab="first difference")
acf(diffY_train, lag.max=50, main="ACF")
pacf(diffY_train, lag.max=50, main="PACF")
```

- No clear indication of exponential decay or lag cut-off in ACF and PACF, so best bet is to try a number of ARIMA models.
- So for power transformed data, the following ARIMA models are proposed:

```{r echo=FALSE}
arima_params = data.frame(p=character(), d=character(), q=character())
for (p in 0:6) {
    for (q in 0:6) {
        if ((p != 0) | (q != 0)) {
            arima_params[nrow(arima_params) + 1,] = c(p, 1, q)
        }
    }
}

arima_params
```


```{r}
df = read.csv('/Users/pivaldhingra/Desktop/University courses/STAT 443 project /Data_Group24.csv')
Y = ts(df$price)
pwrY = Y^0.075

test = read.csv('test.csv')
Y_test = ts(test$price)
# pwrY_test = Y_test^0.075
```

```{r}
length(Y_test)
```

```{r}
min_apse = Inf 
min_apse_params = c()
best_preds = c()
best_lower = c()
best_upper = c()
for(i in 1:nrow(arima_params)) {
    row = arima_params[i,]
    p = strtoi(row[1,"p"])
    d = strtoi(row[1,"d"])
    q = strtoi(row[1,"q"])
    
    forecast = astsa::sarima.for(pwrY_train, n.ahead=1318, p, d, q, plot=FALSE)
    lower <- forecast$pred-1.96*forecast$se
    upper <- forecast$pred+1.96*forecast$se
    pwrY_pred = forecast$pred
    apse = mse(as.vector(Y_test), as.vector(pwrY_pred^(1/0.075)))
    if (apse < min_apse) {
        min_apse = apse
        min_apse_params = row
        best_preds = pwrY_pred
        best_lower = lower
        best_upper = upper
    }
}

print(paste("Minimum APSE: ", min_apse))
print(min_apse_params)
```

### Selected ARIMA model

```{r}
row = min_apse_params[1,]
p = strtoi(row[1,"p"])
d = strtoi(row[1,"d"])
q = strtoi(row[1,"q"])

sarima(pwrY_train, p, d, q)
```


```{r}

plot(pwrY, main="Forecasting", ylab="power transformed price")
lines(pwrY_pred,col='red',type='l',pch='*') 
lines(lower,col='blue',lty=2)
lines(upper,col='blue',lty=2)
```

```{r}
plot(Y, main="Forecasting", ylab="price")
lines(pwrY_pred^(1/0.075),col='red',type='l',pch='*') 
lines(lower^(1/0.075),col='blue',lty=2)
lines(upper^(1/0.075),col='blue',lty=2)
```
